### ISSUE TITLE
Using with V Server

### ISSUE THREAD

**Issue by DieProgrammIDE** [niccokunzmann/freifunk-website-proxy#6]
Hi,
i would like to ask if it is possible to run this on Docker Incompatible Computer (2009 Mac Mini, doesn't have the required CPU ext). Also is this suitable to make all devices in a Private Network available from a Server/VPN to have your private network everywhere

**Comment by niccokunzmann** [comment]
> i would like to ask if it is possible to run this on Docker Incompatible Computer (2009 Mac Mini, doesn't have the required CPU ext).

Hi, it is possible to run this on such a computer. The Dockerfile contains a recipe for alpine linux.
What needs to be installed, is python3, the packages in requirements.txt and nginx, the web server.

> Also is this suitable to make all devices in a Private Network available from a Server/VPN to have your private network everywhere

This is a proxy for http requests. HTTP works on top of the IP layer, as such you do not have your whole network exposed on IP level. It is possible to expose HTTP servers with this to all clients which can access this server.

If you are in Potsdam, using Freifunk and the Potsdam VPN, you can also use my deployment which runs at home http://ffp.quelltext.eu/ or, of cause, set up your own.

**Comment by AnderCrafter** [comment]
Thank You or Your Answer,
as i am already using my own VPN on my Server i am already able to do this, but i need to install the VPN Connector on every Computer.
